# Generated by Django 4.2.9 on 2024-01-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("proveedor", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                ("cantidad", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
